/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasurerVaultForExec,
  ITreasurerVaultForExecInterface,
} from "../../StrategyExecutor.sol/ITreasurerVaultForExec";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "allocateToYieldFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITreasurerVaultForExec__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasurerVaultForExecInterface {
    return new Interface(_abi) as ITreasurerVaultForExecInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITreasurerVaultForExec {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITreasurerVaultForExec;
  }
}
