/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BudgetControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canSpend"
      | "currentDayStart"
      | "dailyLimitWei"
      | "recordSpend"
      | "setDailyLimit"
      | "spentToday"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DailyLimitSet" | "DayReset" | "SpendRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canSpend",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentDayStart",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyLimitWei",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSpend",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "spentToday",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "canSpend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentDayStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyLimitWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spentToday", data: BytesLike): Result;
}

export namespace DailyLimitSetEvent {
  export type InputTuple = [user: AddressLike, limitWei: BigNumberish];
  export type OutputTuple = [user: string, limitWei: bigint];
  export interface OutputObject {
    user: string;
    limitWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DayResetEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendRecordedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    newTotalToday: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    newTotalToday: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    newTotalToday: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BudgetController extends BaseContract {
  connect(runner?: ContractRunner | null): BudgetController;
  waitForDeployment(): Promise<this>;

  interface: BudgetControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canSpend: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [[boolean, bigint] & { allowed: boolean; remaining: bigint }],
    "view"
  >;

  currentDayStart: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  dailyLimitWei: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  recordSpend: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDailyLimit: TypedContractMethod<
    [limitWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  spentToday: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canSpend"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [[boolean, bigint] & { allowed: boolean; remaining: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentDayStart"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyLimitWei"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordSpend"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyLimit"
  ): TypedContractMethod<[limitWei: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spentToday"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "DailyLimitSet"
  ): TypedContractEvent<
    DailyLimitSetEvent.InputTuple,
    DailyLimitSetEvent.OutputTuple,
    DailyLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "DayReset"
  ): TypedContractEvent<
    DayResetEvent.InputTuple,
    DayResetEvent.OutputTuple,
    DayResetEvent.OutputObject
  >;
  getEvent(
    key: "SpendRecorded"
  ): TypedContractEvent<
    SpendRecordedEvent.InputTuple,
    SpendRecordedEvent.OutputTuple,
    SpendRecordedEvent.OutputObject
  >;

  filters: {
    "DailyLimitSet(address,uint256)": TypedContractEvent<
      DailyLimitSetEvent.InputTuple,
      DailyLimitSetEvent.OutputTuple,
      DailyLimitSetEvent.OutputObject
    >;
    DailyLimitSet: TypedContractEvent<
      DailyLimitSetEvent.InputTuple,
      DailyLimitSetEvent.OutputTuple,
      DailyLimitSetEvent.OutputObject
    >;

    "DayReset(address)": TypedContractEvent<
      DayResetEvent.InputTuple,
      DayResetEvent.OutputTuple,
      DayResetEvent.OutputObject
    >;
    DayReset: TypedContractEvent<
      DayResetEvent.InputTuple,
      DayResetEvent.OutputTuple,
      DayResetEvent.OutputObject
    >;

    "SpendRecorded(address,uint256,uint256)": TypedContractEvent<
      SpendRecordedEvent.InputTuple,
      SpendRecordedEvent.OutputTuple,
      SpendRecordedEvent.OutputObject
    >;
    SpendRecorded: TypedContractEvent<
      SpendRecordedEvent.InputTuple,
      SpendRecordedEvent.OutputTuple,
      SpendRecordedEvent.OutputObject
    >;
  };
}
