/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BudgetController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BudgetController__factory>;
    getContractFactory(
      name: "MockLPPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockLPPool__factory>;
    getContractFactory(
      name: "ITreasurerVaultForExec",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITreasurerVaultForExec__factory>;
    getContractFactory(
      name: "StrategyExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StrategyExecutor__factory>;
    getContractFactory(
      name: "SubscriptionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SubscriptionManager__factory>;
    getContractFactory(
      name: "TreasurerVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TreasurerVault__factory>;

    getContractAt(
      name: "BudgetController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BudgetController>;
    getContractAt(
      name: "MockLPPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockLPPool>;
    getContractAt(
      name: "ITreasurerVaultForExec",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITreasurerVaultForExec>;
    getContractAt(
      name: "StrategyExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StrategyExecutor>;
    getContractAt(
      name: "SubscriptionManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SubscriptionManager>;
    getContractAt(
      name: "TreasurerVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TreasurerVault>;

    deployContract(
      name: "BudgetController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BudgetController>;
    deployContract(
      name: "MockLPPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockLPPool>;
    deployContract(
      name: "ITreasurerVaultForExec",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITreasurerVaultForExec>;
    deployContract(
      name: "StrategyExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StrategyExecutor>;
    deployContract(
      name: "SubscriptionManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubscriptionManager>;
    deployContract(
      name: "TreasurerVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TreasurerVault>;

    deployContract(
      name: "BudgetController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BudgetController>;
    deployContract(
      name: "MockLPPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockLPPool>;
    deployContract(
      name: "ITreasurerVaultForExec",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITreasurerVaultForExec>;
    deployContract(
      name: "StrategyExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StrategyExecutor>;
    deployContract(
      name: "SubscriptionManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubscriptionManager>;
    deployContract(
      name: "TreasurerVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TreasurerVault>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
