/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SubscriptionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelSubscription"
      | "createSubscription"
      | "depositPrepaid"
      | "executeSubscription"
      | "prepaidBalance"
      | "subscriptionCount"
      | "subscriptions"
      | "withdrawPrepaid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PrepaidDeposit"
      | "PrepaidWithdraw"
      | "SubscriptionCancelled"
      | "SubscriptionCreated"
      | "SubscriptionExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPrepaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "prepaidBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPrepaid",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPrepaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepaidBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPrepaid",
    data: BytesLike
  ): Result;
}

export namespace PrepaidDepositEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrepaidWithdrawEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    payer: AddressLike,
    recipient: AddressLike,
    amountWei: BigNumberish,
    periodSeconds: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    payer: string,
    recipient: string,
    amountWei: bigint,
    periodSeconds: bigint
  ];
  export interface OutputObject {
    id: bigint;
    payer: string;
    recipient: string;
    amountWei: bigint;
    periodSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionExecutedEvent {
  export type InputTuple = [id: BigNumberish, when: BigNumberish];
  export type OutputTuple = [id: bigint, when: bigint];
  export interface OutputObject {
    id: bigint;
    when: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionManager extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionManager;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelSubscription: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSubscription: TypedContractMethod<
    [
      recipient: AddressLike,
      amountWei: BigNumberish,
      periodSeconds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  depositPrepaid: TypedContractMethod<[], [void], "payable">;

  executeSubscription: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  prepaidBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  subscriptionCount: TypedContractMethod<[], [bigint], "view">;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        payer: string;
        recipient: string;
        amountWei: bigint;
        periodSeconds: bigint;
        nextDue: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  withdrawPrepaid: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSubscription"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amountWei: BigNumberish,
      periodSeconds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositPrepaid"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "executeSubscription"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "prepaidBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscriptionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        payer: string;
        recipient: string;
        amountWei: bigint;
        periodSeconds: bigint;
        nextDue: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawPrepaid"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "PrepaidDeposit"
  ): TypedContractEvent<
    PrepaidDepositEvent.InputTuple,
    PrepaidDepositEvent.OutputTuple,
    PrepaidDepositEvent.OutputObject
  >;
  getEvent(
    key: "PrepaidWithdraw"
  ): TypedContractEvent<
    PrepaidWithdrawEvent.InputTuple,
    PrepaidWithdrawEvent.OutputTuple,
    PrepaidWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionExecuted"
  ): TypedContractEvent<
    SubscriptionExecutedEvent.InputTuple,
    SubscriptionExecutedEvent.OutputTuple,
    SubscriptionExecutedEvent.OutputObject
  >;

  filters: {
    "PrepaidDeposit(address,uint256)": TypedContractEvent<
      PrepaidDepositEvent.InputTuple,
      PrepaidDepositEvent.OutputTuple,
      PrepaidDepositEvent.OutputObject
    >;
    PrepaidDeposit: TypedContractEvent<
      PrepaidDepositEvent.InputTuple,
      PrepaidDepositEvent.OutputTuple,
      PrepaidDepositEvent.OutputObject
    >;

    "PrepaidWithdraw(address,uint256)": TypedContractEvent<
      PrepaidWithdrawEvent.InputTuple,
      PrepaidWithdrawEvent.OutputTuple,
      PrepaidWithdrawEvent.OutputObject
    >;
    PrepaidWithdraw: TypedContractEvent<
      PrepaidWithdrawEvent.InputTuple,
      PrepaidWithdrawEvent.OutputTuple,
      PrepaidWithdrawEvent.OutputObject
    >;

    "SubscriptionCancelled(uint256)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionExecuted(uint256,uint256)": TypedContractEvent<
      SubscriptionExecutedEvent.InputTuple,
      SubscriptionExecutedEvent.OutputTuple,
      SubscriptionExecutedEvent.OutputObject
    >;
    SubscriptionExecuted: TypedContractEvent<
      SubscriptionExecutedEvent.InputTuple,
      SubscriptionExecutedEvent.OutputTuple,
      SubscriptionExecutedEvent.OutputObject
    >;
  };
}
