/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TreasurerVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allocateToYield"
      | "allocateToYieldFor"
      | "autoSaveBps"
      | "balances"
      | "deposit"
      | "owner"
      | "setAutoSaveBps"
      | "setStrategyExecutor"
      | "strategyExecutor"
      | "transferOwnership"
      | "withdraw"
      | "withdrawFromYield"
      | "yieldAllocated"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoSaveUpdated"
      | "Deposited"
      | "Withdrawn"
      | "YieldAllocated"
      | "YieldWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allocateToYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allocateToYieldFor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoSaveBps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAutoSaveBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategyExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldAllocated",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allocateToYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateToYieldFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoSaveBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAutoSaveBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStrategyExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldAllocated",
    data: BytesLike
  ): Result;
}

export namespace AutoSaveUpdatedEvent {
  export type InputTuple = [user: AddressLike, bps: BigNumberish];
  export type OutputTuple = [user: string, bps: bigint];
  export interface OutputObject {
    user: string;
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldAllocatedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldWithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasurerVault extends BaseContract {
  connect(runner?: ContractRunner | null): TreasurerVault;
  waitForDeployment(): Promise<this>;

  interface: TreasurerVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allocateToYield: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  allocateToYieldFor: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  autoSaveBps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  setAutoSaveBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStrategyExecutor: TypedContractMethod<
    [exec: AddressLike],
    [void],
    "nonpayable"
  >;

  strategyExecutor: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawFromYield: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldAllocated: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allocateToYield"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allocateToYieldFor"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "autoSaveBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAutoSaveBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStrategyExecutor"
  ): TypedContractMethod<[exec: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "strategyExecutor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFromYield"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yieldAllocated"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AutoSaveUpdated"
  ): TypedContractEvent<
    AutoSaveUpdatedEvent.InputTuple,
    AutoSaveUpdatedEvent.OutputTuple,
    AutoSaveUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "YieldAllocated"
  ): TypedContractEvent<
    YieldAllocatedEvent.InputTuple,
    YieldAllocatedEvent.OutputTuple,
    YieldAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "YieldWithdrawn"
  ): TypedContractEvent<
    YieldWithdrawnEvent.InputTuple,
    YieldWithdrawnEvent.OutputTuple,
    YieldWithdrawnEvent.OutputObject
  >;

  filters: {
    "AutoSaveUpdated(address,uint256)": TypedContractEvent<
      AutoSaveUpdatedEvent.InputTuple,
      AutoSaveUpdatedEvent.OutputTuple,
      AutoSaveUpdatedEvent.OutputObject
    >;
    AutoSaveUpdated: TypedContractEvent<
      AutoSaveUpdatedEvent.InputTuple,
      AutoSaveUpdatedEvent.OutputTuple,
      AutoSaveUpdatedEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;

    "YieldAllocated(address,uint256)": TypedContractEvent<
      YieldAllocatedEvent.InputTuple,
      YieldAllocatedEvent.OutputTuple,
      YieldAllocatedEvent.OutputObject
    >;
    YieldAllocated: TypedContractEvent<
      YieldAllocatedEvent.InputTuple,
      YieldAllocatedEvent.OutputTuple,
      YieldAllocatedEvent.OutputObject
    >;

    "YieldWithdrawn(address,uint256)": TypedContractEvent<
      YieldWithdrawnEvent.InputTuple,
      YieldWithdrawnEvent.OutputTuple,
      YieldWithdrawnEvent.OutputObject
    >;
    YieldWithdrawn: TypedContractEvent<
      YieldWithdrawnEvent.InputTuple,
      YieldWithdrawnEvent.OutputTuple,
      YieldWithdrawnEvent.OutputObject
    >;
  };
}
