/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StrategyExecutorInterface extends Interface {
  getFunction(
    nameOrSignature: "agentOf" | "executeAllocateYield" | "setAgent" | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentSet" | "StrategyYieldAllocate"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAllocateYield",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "agentOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeAllocateYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace AgentSetEvent {
  export type InputTuple = [user: AddressLike, agent: AddressLike];
  export type OutputTuple = [user: string, agent: string];
  export interface OutputObject {
    user: string;
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyYieldAllocateEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    action: string
  ];
  export type OutputTuple = [user: string, amount: bigint, action: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    action: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyExecutor;
  waitForDeployment(): Promise<this>;

  interface: StrategyExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  executeAllocateYield: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, actionLabel: string],
    [void],
    "nonpayable"
  >;

  setAgent: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "executeAllocateYield"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, actionLabel: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentSet"
  ): TypedContractEvent<
    AgentSetEvent.InputTuple,
    AgentSetEvent.OutputTuple,
    AgentSetEvent.OutputObject
  >;
  getEvent(
    key: "StrategyYieldAllocate"
  ): TypedContractEvent<
    StrategyYieldAllocateEvent.InputTuple,
    StrategyYieldAllocateEvent.OutputTuple,
    StrategyYieldAllocateEvent.OutputObject
  >;

  filters: {
    "AgentSet(address,address)": TypedContractEvent<
      AgentSetEvent.InputTuple,
      AgentSetEvent.OutputTuple,
      AgentSetEvent.OutputObject
    >;
    AgentSet: TypedContractEvent<
      AgentSetEvent.InputTuple,
      AgentSetEvent.OutputTuple,
      AgentSetEvent.OutputObject
    >;

    "StrategyYieldAllocate(address,uint256,string)": TypedContractEvent<
      StrategyYieldAllocateEvent.InputTuple,
      StrategyYieldAllocateEvent.OutputTuple,
      StrategyYieldAllocateEvent.OutputObject
    >;
    StrategyYieldAllocate: TypedContractEvent<
      StrategyYieldAllocateEvent.InputTuple,
      StrategyYieldAllocateEvent.OutputTuple,
      StrategyYieldAllocateEvent.OutputObject
    >;
  };
}
